### ISSUE TITLE
CHAPTER 10 일급 함수 I

### ISSUE THREAD

**Issue by mugglim** [Nabaang/ssok-ssok-functional-coding#10]
공감가는 내용, 토론해보고 싶은 내용, 다른 사람의 의견을 들어보고 싶은 내용 가져오기~

**Comment by mugglim** [comment]
### 공감가는 내용
- 함수에서 반복되는 행위를 콜백 함수로 추상화하는 리팩터링.
- 반복되는 함수를 하나의 함수로 추상화하는 리팩터링. 
  - 함수가 역할은 동일한데 인자에 의존적인 경우  ex) `setPriceByName` => `setFieldByName` (setFieldByName을 한번 더 추상화 하고 싶긴 하다.)

### 토론해보고 싶은 내용
- 왜 일급이 아닌 값을 일급 함수로 표현하려고 할까요?

**Comment by kukucorn** [comment]
### 신기했던 내용
- 함수 인자로 넘겨주는 값이 문자열이었는데, 값으로 사용되는 문자열은 큰따옴표를 쓰고 키로 사용되는 문자열은 작은따옴표를 사용

### 토론해 보고 싶은 내용
- 책에서도 이거 고민할 시간에 숙면하는 게 낫다고 했지만, 동적 언어 vs 정적 언어 둘을 비교하기보다는 어떤 장, 단점이 있는지?

**Comment by jihoho** [comment]
### 공감가는 내용
- (데이터 지향) 데이터를 그대로 사용하는 것이 여러가지 방법으로 해석이 되고 제한이 없다. 하지만 제한된 API로 정의하면 데이터를 제대로 활용할 수 없고 미래에 어떤 방법으로 해석될지 모르기 때문에 호출 그래프에서 하위 계층에서는 데이터를 그대로 사용하는 것이 유지보수 측면에서 더 유리할 것 같다는 생각이 듬.
- 필드명을 문자열로 사용할 경우에 문자열의 오타로 인해 생기는 버그가 우려됨. 이러한 점에서 타입이 일관성을 보장해주는 정적 타입 언어가 유리함. BUT 통신 과정에 있는 것은 모두 문자열이고, 데이터 형식이 있다해도 바이트일 뿐, API 역시 받은 데이터를 런타임에 체크를 해야 하고, 많은 비지니스 시스템을 동적 타입으로 운영이 잘되고 있음.

 
### 토론해보고 싶은 내용
- 인라인 함수 (개발 편의성 VS 성능 저하)
