### ISSUE TITLE
CHAPTER 11 일급 함수 II 

### ISSUE THREAD

**Issue by mugglim** [Nabaang/ssok-ssok-functional-coding#15]
공감가는 내용, 토론해보고 싶은 내용, 다른 사람의 의견을 들어보고 싶은 내용 가져오기~

**Comment by mugglim** [comment]
### 공감가는 내용
- 반복되는 부분과 반복되지 않는 부분을 구분 후, 커링을 통해 HOC로 변환하는 작업
```js
const withTryCatch = (callback, onError) => (...args) => {
  try{
     callback.apply(null, args);
  } catch(error){
     onError(error);
  }
}
```
- 과도하게 함수의 로직을 고차함수로 추상화하면 오히려 코드의 가독성을 떨어트릴 수 있다.

**Comment by kukucorn** [comment]
### 공감 가는 내용

일급 함수, 고차 함수라는 개념은 강력한 기능이지만 항상 직관적인 방법(일반적인 방법을 의미하는 것 같음)과 비교를 해야 한다. 가독성이 증가했는지? 코드 중복을 얼마나 없앴는지? 코드가 하는 일을 쉽게 알 수 있는지?…

### 토론해 볼 내용

이번 장이랑 연관 없는 내용이지만,, 에러 처리에 대해 나와서 ㅎㅎ;;
어떤 요청에 대해 에러가 발생하면 catch로 에러에 대한 처리를 하고 요청을 계속해서 처리해야 할까? 아니면 에러가 발생했으니 거기서 요청을 중단해야 할까?

**Comment by jihoho** [comment]
### 공감 안가는 내용

리턴값인 함수를 변수로 사용할 경우 function 키워드로 정의 할때와 헷갈릴 수 있지만
함수명을 동사형 그리고 변수명은 명사를 사용해서 구분 할 수 있다?
그렇지 않은 경우도 있지 않나?

### 토론해 볼 내용

마지막 부분에서 withLogging() 함수에서 모든 코드를 계속 감싸줘야 했었음.
이를 익명함수를 리턴하는 wrapLogging()으로 개선을 했는데, 중복이 없어 진게 맞는건지...
