### ISSUE TITLE
CHAPTER 12 함수형 반복 

### ISSUE THREAD

**Issue by mugglim** [Nabaang/ssok-ssok-functional-coding#16]
공감가는 내용, 토론해보고 싶은 내용, 다른 사람의 의견을 들어보고 싶은 내용 가져오기~

**Comment by mugglim** [comment]
### 공감가는 내용
- 시퀀스 관점에서 map(), filter(), reduce()을 바라보는 점
- 직접 map과 같은 함수를 구현해보면서 어떻게 동작하는지 고민해보는 점

### 다른 사람의 의견을 들어보고 싶은 내용
- reduce를 통한 실행 취소/실행 복귀를 구현하는 방법

**Comment by kukucorn** [comment]
### 공감 가는 내용

- reduce를 이용해서 min or max를 구하는 방법(시퀀스를 하나의 값으로 만듦)

### 토론해 볼 내용 

- 고차 함수는 항상 반복문보다 옳은가?

**Comment by jihoho** [comment]
### 공감 가는 내용
map,filter,reduce 고차 함수를 도출하는 과정
map 사용 시 배열의 항목을 확인하지 않기 때문에 조심해야 함.(null을 제거하는 filter를 사용하는게 안전)

### 토론해 볼 내용 

고차함수가 반복문보다 빠른가?
