### ISSUE TITLE
CHAPTER 13 함수형 도구 체이닝

### ISSUE THREAD

**Issue by mugglim** [Nabaang/ssok-ssok-functional-coding#17]
공감가는 내용, 토론해보고 싶은 내용, 다른 사람의 의견을 들어보고 싶은 내용 가져오기~

**Comment by kukucorn** [comment]
### 공감 가는 내용

- 프로그래밍 관점에서 항등 함수(자기 자신을 반환)라는 개념이 재미있었다.
- 절차 지향적 프로그래밍보다 함수형 프로그래밍으로 체이닝 하는 게 더 가독성이 좋다. (337p)
  - 파이프라인처럼 이전 단계가 끝나고 다음 단계가 시작한다.(전 단계를 생각하지 않아도 됨)

### 다른 사람의 의견

- 고차 함수 전체를 함수로 vs 고차 함수에서 사용하는 콜백을 함수로 (326p)

**Comment by mugglim** [comment]
### 공감가는 내용
- 절차 지향 구문을 함수형 구문의 계산으로 분리하는 방법 (ex) 반복문 => filter)
- 여러 함수형 계산을 하나의 체인으로 묶어 가독성을 높이는 행위

### 공유하고 싶은 내용
- 책을 읽을수록 타입스크립트를 사용하고 싶네요.. (타입을 원해!!)

```ts
// p.341
type Products = {
    name : string;
    quantity: number;
}

const products : Products[] = [
    {'name' : 'shirt', 'quantity' : 10},
    {'name' : 'pen', 'quantity' : 20},
    {'name' : 'note', 'quantity' : 30},
    {'name' : 'bag', 'quantity' : 40},
]

const pluck = <T extends object, K extends keyof T>(array: T[], field : K) => array.map(element => element[field])
const productQuantites = pluck(products, 'quantity')
```

**Comment by jihoho** [comment]
### 공감가는 내용
- 체이닝을 통해 과감하게 배열 전체를 다루면서 여러 단계를 파이프라인으로 사용하는 것이 더 명확하고 읽기 쉬움.  (병목이 발생하면 stream fusion~!)
- java의 람다나 스트림 API 를 단순히 코드가 간결해진다, stream 는 이유로 많이 사용을 했었는데, 데이터 불변성을 위해 데이터가 변경되지 않는다는 점과, 그로인해 발생하는 오버헤드를 생각해볼 수 있었음.

### 토론하고 싶은 내용
- Event Sourcing?? 장바구니에 제품 추가 및 제거 기능에 적용한다면??
