### ISSUE TITLE
CHAPTER 9 계층형 설계

### ISSUE THREAD

**Issue by mugglim** [Nabaang/ssok-ssok-functional-coding#9]
공감가는 내용, 토론해보고 싶은 내용, 다른 사람의 의견을 들어보고 싶은 내용 가져오기~

**Comment by mugglim** [comment]
### 공감가는 내용
- 테스트 커버리지를 높이는게 중요한 게 아니라, 무엇을 테스트 할지 결정하는 게 중요.
- 비 기능적 요구사항을 함수형 프로그래밍 관점으로 생각해 볼 수 있었음.
 
### 토론해보고 싶은 내용
- 추상화 계층의 최상위 계층 함수를 언제 테스트 할지?? (ex) 배포 전))
  - = 액션을 언제 테스트 할지?

**Comment by jihoho** [comment]
### 공감가는 내용
- 카피-온-라이트 함수(불변성 지향)는 가장 낮은 계층(시간이 지나도 변하지않는 코드)
  - 성능적으로 이슈가 있을 수 있지만 현대 머신의 속도가 빠름 -> 요즘 트렌드에 맞는 패러다임이라는 생각이 듬. 방대한 데이터를 처리하는 동시성과 복잡한 요구 사항에 대한 추상화
- 추상화의 개념은 객체지향에서 많이 접해 익숙했지만, 함수형 패러다임 기반에서 계층형 구조를 생각해볼 수 있었음. 
 
### 토론해보고 싶은 내용
- Data Access Layer 계층의 위치 어디?
   - 계층형 구조에서 Presentation -> Business -> service -> persistence layer -> Database Layer
   - 재사용성을 고려한다면 하위 계층에 위치 해야 하지만 부수효과가 있기에...

**Comment by kukucorn** [comment]
### 공감가는 내용

- 하려는 일이 적은 함수로 잘할 수 있나요? 목적에 맞게 바꾸려고 하고 있나요?
- 책에서는 추상화 벽이라는 개념으로 설명하고 있는데, 이게 하나의 코드 뭉치에서 적용될 수도 있지만 api 같이 여러 팀에서 사용하고 소통하는 공간에도 적용이 될 수 있을 것 같다.

### 토론해보고 싶은 내용

- 일반적으로 한 줄짜리 코드는 여러 구체화 수준이 섞일 일이 없기 때문에 좋은 코드라는 표시이다
    - 한 줄짜리 코드를 함수로 만들어야 할까? 라는 생각과 추상화의 레벨이 다르다면 한 줄짜리 함수도 짜야한다?
